config/routes.rb
Paporeto::Application.routes.draw do
  resources :reader_articles, only: [:new, :create, :show]

  devise_for :users

  namespace :admin do
    resources :users

    resources :categories, path: 'categorias'

    resources :articles, path: 'artigos', path_names: {new: 'criar',edit: 'editar'}
  end

  get 'admin' => 'admin/articles#index'  

  mount Uploadbox::Engine => '/uploadbox', as: :uploadbox

  root 'home#index'

  resources :categories, path: '', only: [:index,:show] do
    resources :articles, path: '', only: [:index,:show]
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, :summary, :body, :category, presence: true

  uploads_one :picture, thumb: [90,80],
                        small: [260, 196],
                        regular: [580, 240],
                        large: [940,380],
                        full: [1280, 493]

  belongs_to :category

  paginates_per 15

  default_scope -> {order(published_at: :desc)}

  def self.published
    where('published_at <= ?',Time.now)
  end

  def self.featured
    where(featured: true)
  end

  def to_param
    "#{id} #{title}".parameterize
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  layout 'admin'
  before_action :authenticate_user!
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.page(params[:page])
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.attach_picture(params[:picture_id])

    respond_to do |format|
      if @article.save
        format.html { redirect_to [:admin, @article], notice: 'Artigo salvo.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @article.attach_picture(params[:picture_id])
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to [:admin, @article], notice: 'Artigo salvo!' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :summary, :body, :category_id, :featured, :featured_at_home, :published_at)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @category = Category.find(params[:category_id])

    @articles = @category.articles.published.where(featured: false).limit(8)
    @featured = @category.articles.featured.first
  end

  def show
    @article = Article.find(params[:id])
    @relateds = @article.category.articles.where.not(id: @article.id).limit(3)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_form.html.slim
= simple_form_for([:admin, @article]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.uploader :picture
    = f.association :category, prompt: 'Escolha uma categoria'
    = f.input :summary
    = f.input :featured, inline_label: true, label: false
    = f.input :featured_at_home, inline_label: true, label: false
    = f.input :published_at
    = f.input :body, input_html: {rows: 15, class: 'input-xxlarge'}

  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    = link_to 'Cancelar', admin_articles_path, class: 'btn'

app/views/admin/articles/edit.html.slim
h1 Editar artigo

== render 'form'

app/views/admin/articles/index.html.slim
h1 Artigos

table.table.table-striped
  tr
    th Título
    th Resumo
    th Categoria
    th

  - @articles.each do |article|
    tr
      td = article.title
      td = article.summary
      td = article.category.name
      td
        div align="right"
          .btn-group
            = link_to 'Ver', [:admin, article], class: 'btn btn-small'
            = link_to 'Editar', edit_admin_article_path(article), class: 'btn btn-small'
            = link_to 'Excluir', [:admin, article], class: 'btn btn-small btn-danger', :confirm => 'Tem certeza?', :method => :delete

= paginate @articles, theme: 'twitter-bootstrap'

br

= link_to 'Novo artigo', new_admin_article_path, class: 'btn btn-primary'

app/views/admin/articles/new.html.slim
h1 Novo artigo

== render 'form'

app/views/admin/articles/show.html.slim
h1 = @article.title
p = @article.summary
div align="right"
  span.label = @article.category.name
hr
= simple_format @article.body

= link_to 'Editar', edit_admin_article_path(@article)

//= link_to 'Ok', articles_path