config/routes.rb
Paporeto::Application.routes.draw do
  resources :reader_articles, only: [:new, :create, :show]

  devise_for :users

  namespace :admin do
    resources :users

    resources :categories, path: 'categorias'

    resources :articles, path: 'artigos', path_names: {new: 'criar',edit: 'editar'}
  end

  get 'admin' => 'admin/articles#index'  

  mount Uploadbox::Engine => '/uploadbox', as: :uploadbox

  root 'home#index'

  resources :categories, path: '', only: [:index,:show] do
    resources :articles, path: '', only: [:index,:show]
  end
end

app/views/layouts/admin.slim
doctype html
html
  head
    title PapoReto
    = stylesheet_link_tag    "admin", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "admin", "data-turbolinks-track" => true
    = csrf_meta_tags

  body
    .container
      .navbar
        .navbar-inner
          = link_to 'Paporeto', root_path, class: 'brand'
          - if current_user
            ul.nav
              li class="#{'active' if params[:controller] == 'admin/articles'}"
                = link_to 'Artigos', admin_articles_path
              li class="#{'active' if params[:controller] == 'admin/categories'}"
                = link_to 'Categorias', admin_categories_path
              li class="#{'active' if params[:controller] == 'admin/users'}"
                = link_to 'Admins', admin_users_path
            ul.nav.pull-right
              li
                - if current_user.name.blank?
                  = link_to current_user.email, '#'
                - else
                  = link_to current_user.name, '#'
              li
                = link_to 'Sair', destroy_user_session_path, method: :delete
      - if notice
        .alert
          button type="button" class="close" data-dismiss="alert" &times;
          = notice

      - if alert
          .alert.alert-error
            button type="button" class="close" data-dismiss="alert" &times;
            = alert
      = yield
    footer
      br
      br
      .navbar-inner align='center'
        table
          tr height='8px'
            td
          tr
            td
              strong color="#000000"
                = 'Curso Startae - Leonardo'

app/views/layouts/application.slim
doctype html
/[if lt IE 7]
  | <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang='#{I18n.locale}'>
/[if IE 7]
  | <html class="no-js lt-ie9 lt-ie8" lang='#{I18n.locale}'>
/[if IE 8]
  | <html class="no-js lt-ie9" lang='#{I18n.locale}'>
/[if IE 9]
  | <html class="no-js ie ie9" lang='#{I18n.locale}'>
| <!--[if (gte IE 9)|!(IE)]<!-->
html.no-js lang='#{I18n.locale}'
  | <!--<![endif]-->
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=edge'
    - if @title.present?
      title = 'PapoReto::' + @title
    - else
      title PapoReto.com — Notícias direto ao ponto, sem enrolação!
    meta name="description" content=""
    meta name='author' content='Startaê — http://www.startae.com.br'
    = csrf_meta_tags
    = favicon_link_tag 'favicon.png', type: 'image/x-icon'
    = stylesheet_link_tag 'application', media: 'all'
  body class="#{{@page_class}}"
    = render 'shared/header'
    = yield
    = render 'shared/footer'
    = render 'shared/development' if Rails.env.development?
    = javascript_include_tag 'application'